#!/usr/bin/env bash
TOOLS_DIR="/usr/local/bin/aadisctools"
case $1 in 
	'-c')
	$TOOLS_DIR/checkaadi ${@:2}
	exit $?
	;;
	'-n')
	$TOOLS_DIR/makeaadi ${@:2}
	exit $?
	;;
	'-s')
	$TOOLS_DIR/showaadi ${@:2}
	exit $?
	;;
	'-r')
	$TOOLS_DIR/renameaadi ${@:2}
	exit $?
	;;
	'-R')
	$TOOLS_DIR/removeaadi ${@:2}
	exit $?
	;;
	'-l')
	$TOOLS_DIR/listaadi ${@:2}
	exit $?
	;;
	'--help')
	echo -e $(cat $TOOLS_DIR/helptext)  
	exit $?
	;;
	*)
	echo -e "Error! WTF WAS THAT\nPlease use \"aadisc --help\" for help">&2
	exit 1
	;;
esac
