#!/usr/bin/env bash
ERRRED="\033[1;31m"
ENDL="\033[0m"

if [[ $# >1 ]]; then
	echo -e "${ERRRED}ERROR! TOO MANY ARGUEMENTS${ENDL}"
	exit 1
elif [[ $# < 1  ]]; then
	echo -e "${ERRRED}ERROR! TOO FEW ARGUEMENTS${ENDL}" 
	exit 1
fi

aliasfile=$HOME/.aadi_aliases
tempfile=$HOME/.tempaliasaadi


lines=$(grep "alias"* $aliasfile)
IFS=$'\n'
/usr/local/bin/aadisctools/checkaadi $1
[[ $? != 0 ]] && exit 1

read -p "Where do you want \"$1\" to lead? " newpath
[[ $? != 0 ]] && exit 1

if [ -e "$newpath" ]; then
else
	echo -e "${ERRRED}ERROR! Path does not exist${ENDL}"
	exit 1
fi

touch $tempfile
[[ $? != 0 ]] && exit 1

for line in $lines; do
	if [[ $line == "alias $1="*  ]]; then
		echo "alias $1=\"cd \"$newpath\"\"">>$tempfile
	else	
		echo $line >> $tempfile	
	fi
done

cat $tempfile>$aliasfile
[[ $? != 0 ]] && exit 1

mv $tempfile $HOME/.Tr/

exit 0
 
